# -*- coding: utf-8 -*-
"""NPV + IRR Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDLpb_Fud_XHj14MhEKt7XP4lYoJlW2M
"""

initial_investment = float(input("Enter initial investment: "))
required_return = float(input("Enter required rate of return (e.g. 0.10): "))
years = int(input("Enter number of years: "))

cash_flows = []
for i in range(years):
    cash = float(input(f"Enter cash flow for year {i+1}: "))
    cash_flows.append(cash)

def calculate_npv(cash_flows, rate, initial_investment):
    npv = 0
    year = 1
    for cash in cash_flows:
        npv += cash / (1 + rate) ** year
        year += 1
    return npv - initial_investment

def calculate_irr(cash_flows, initial_investment):
    low = 0.0
    high = 1.0
    tolerance = 1

    for i in range(100):
        rate = (low + high) / 2
        npv = calculate_npv(cash_flows, rate, initial_investment)

        if abs(npv) < tolerance:
            return rate

        if npv > 0:
            low = rate
        else:
            high = rate

    return rate

base_case = cash_flows
best_case = [cash * 1.2 for cash in cash_flows]
worst_case = [cash * 0.8 for cash in cash_flows]

scenarios = {
    "Base Case": base_case,
    "Best Case": best_case,
    "Worst Case": worst_case
}

print("\n=========== ANALYSIS ===========")

results = {}

for name, flows in scenarios.items():
    npv = calculate_npv(flows, required_return, initial_investment)
    irr = calculate_irr(flows, initial_investment)

    print(f"\n--- {name} ---")
    print(f"NPV: {round(npv, 2)}")
    print(f"IRR: {round(irr * 100, 2)}%")

    # Decision
    if npv > 0 and irr > required_return:
        decision = "ACCEPT ✅"
    elif npv > 0:
        decision = "ACCEPT (Risky) ⚠️"
    else:
        decision = "REJECT ❌"

    print("Decision:", decision)

    results[name] = npv

good_cases = 0

for npv in results.values():
    if npv > 0:
        good_cases += 1

print("\n=========== FINAL SUMMARY ===========")

if good_cases == len(results):
    print("Project is SAFE ")
elif good_cases >= 2:
    print("Project is MODERATE RISK ")
else:
    print("Project is HIGH RISK ")

# ----------- SAFE USER INPUT -----------

# Initial Investment
while True:
    try:
        initial_investment = float(input("Enter initial investment: "))
        if initial_investment > 0:
            break
        else:
            print("❌ Investment must be positive")
    except:
        print("❌ Please enter a number")

# Required Return
while True:
    try:
        required_return = float(input("Enter required rate of return (e.g. 0.10): "))
        if 0 < required_return < 1:
            break
        else:
            print("❌ Enter a value between 0 and 1")
    except:
        print("❌ Please enter a number")

# Number of Years
while True:
    try:
        years = int(input("Enter number of years: "))
        if years > 0:
            break
        else:
            print("❌ Years must be positive")
    except:
        print("❌ Please enter a whole number")

# Cash Flows
cash_flows = []
for i in range(years):
    while True:
        try:
            cash = float(input(f"Enter cash flow for year {i+1}: "))
            cash_flows.append(cash)
            break
        except:
            print("❌ Please enter a number")

# ----------- NPV FUNCTION -----------

def calculate_npv(cash_flows, rate, initial_investment):
    npv = 0
    year = 1
    for cash in cash_flows:
        npv += cash / (1 + rate) ** year
        year += 1
    return npv - initial_investment

# ----------- IRR FUNCTION (FAST) -----------

def calculate_irr(cash_flows, initial_investment):
    low = 0.0
    high = 1.0
    tolerance = 1   # faster

    for _ in range(100):   # fewer iterations
        rate = (low + high) / 2
        npv = calculate_npv(cash_flows, rate, initial_investment)

        if abs(npv) < tolerance:
            return rate

        if npv > 0:
            low = rate
        else:
            high = rate

    return rate

# ----------- SCENARIOS -----------

base_case = cash_flows
best_case = [cash * 1.2 for cash in cash_flows]
worst_case = [cash * 0.8 for cash in cash_flows]

scenarios = {
    "Base Case": base_case,
    "Best Case": best_case,
    "Worst Case": worst_case
}

# ----------- ANALYSIS -----------

print("\n=========== ANALYSIS ===========")

results = {}

for name, flows in scenarios.items():
    npv = calculate_npv(flows, required_return, initial_investment)
    irr = calculate_irr(flows, initial_investment)

    print(f"\n--- {name} ---")
    print(f"NPV: {round(npv, 2)}")
    print(f"IRR: {round(irr * 100, 2)}%")

    # Decision Logic
    if npv > 0 and irr > required_return:
        decision = "ACCEPT ✅"
    elif npv > 0:
        decision = "ACCEPT (Risky) ⚠️"
    else:
        decision = "REJECT ❌"

    print("Decision:", decision)

    results[name] = npv

# ----------- RISK ANALYSIS -----------

good_cases = sum(1 for npv in results.values() if npv > 0)

print("\n=========== FINAL SUMMARY ===========")

if good_cases == len(results):
    print("Project is SAFE ✅")
elif good_cases >= 2:
    print("Project is MODERATE RISK ⚠️")
else:
    print("Project is HIGH RISK ❌")